# numpy 실습

In [10]:
import numpy as np

### array 생성

In [11]:
test_array = np.array(['1', '4', 5, 8], float)

In [12]:
test_array

array([1., 4., 5., 8.])

In [13]:
type(test_array[3])

numpy.float64

In [25]:
test_array.dtype

dtype('float64')

In [15]:
test_array

array([1., 4., 5., 8.])

In [16]:
test_array.shape

(4,)

### shape

In [19]:
vector = [1,2,3,4]
np.array(vector, int).shape

(4,)

In [20]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [21]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape # (층,행,열)

(4, 3, 4)

In [22]:
np.array(tensor, int).ndim # 몇 차원인지?

3

In [23]:
np.array(tensor, int).size # 각 요소 갯수 합

48

### dtype

In [26]:
a = np.array([[1,2,3], [4.5,5,6]], dtype=int)

In [27]:
np.array([[1,2,3], [4.5, '5', '6']], dtype=np.float32).nbytes

24

In [28]:
np.array([[1,2,3], [4.5, '5', '6']], dtype=np.int8).nbytes

6

In [29]:
np.array([[1,2,3], [4.5, '5', '6']], dtype=np.float64).nbytes

48

### reshape

In [30]:
test_matrix = [[1,2,3,4,], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [31]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [32]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [33]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [34]:
np.array(test_matrix).reshape(2,4)

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [35]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [37]:
np.array(test_matrix).reshape(2,-1)

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [38]:
np.array(test_matrix).reshape(2,-1).shape

(2, 4)

In [39]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [40]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

In [44]:
test_matrix = [[[1,2,3,4],[1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

### indexing

In [46]:
test_example = np.array([[1,2,3], [4.5,5,6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
test_example[0][0]

1

In [48]:
test_example[0,0]

1

In [49]:
test_example[0,0]
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
test_example[0][0]
test_example[0,0]

1

In [51]:
test_example = np.array([[1,2,5,8], [1,2,5,8], [1,2,5,8], [1,2,5,8]], int)
test_example[:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [53]:
print(test_example[:,1:3])
print(test_example[1,:2])

[[2 5]
 [2 5]
 [2 5]
 [2 5]]
[1 2]


In [54]:
test_example = np.array([[1,2,3,4,5], [6,7,8,9,10]], int)
test_example[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [55]:
test_example[1,1:3]

array([7, 8])

In [56]:
test_example[1:3]

array([[ 6,  7,  8,  9, 10]])

In [57]:
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [58]:
a[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [59]:
a[:, -1].reshape(2,5)

array([[ 9, 19, 29, 39, 49],
       [59, 69, 79, 89, 99]])

### arange

In [60]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [61]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [62]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### ones, zeros & empty

In [63]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [64]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [65]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [66]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
np.empty(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [68]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [69]:
test_matrix = np.arange(30).reshape(5,6)
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

### eye, identity & digonal

In [70]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [71]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [73]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [76]:
np.diag(matrix, k=1)

array([1, 5])

In [77]:
np.random.uniform(0,1,10).reshape(2,5)

array([[0.44266918, 0.52402121, 0.13553062, 0.30551832, 0.29679556],
       [0.48017248, 0.87441313, 0.33989385, 0.90007529, 0.28965902]])

In [78]:
np.random.normal(0,1,10).reshape(2,5)

array([[ 0.29491831,  0.25839165, -0.47124872,  1.39424015, -0.47148416],
       [-0.90666132, -0.33886759,  1.29031948, -0.67712672,  1.26579005]])

### operation in array

In [79]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
test_array.sum(dtype=np.float)

55.0

In [81]:
test_array = np.arange(1,13).reshape(3,4)
test_array.sum()

78

In [82]:
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [83]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [84]:
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [85]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [86]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [87]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [88]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
test_array.mean(), test_array.mean(axis=0)

(6.5, array([5., 6., 7., 8.]))

In [90]:
test_array.std(), test_array.std(axis=0)

(3.452052529534663, array([3.26598632, 3.26598632, 3.26598632, 3.26598632]))

In [91]:
np.exp(test_array), np.sqrt(test_array)

(array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
        [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
        [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]),
 array([[1.        , 1.41421356, 1.73205081, 2.        ],
        [2.23606798, 2.44948974, 2.64575131, 2.82842712],
        [3.        , 3.16227766, 3.31662479, 3.46410162]]))

### concatenate

In [92]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [93]:
a = np.array([ [1], [2], [3]])
b = np.array([ [2], [3], [4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [94]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.concatenate( (a,b), axis=0)

array([1, 2, 3, 2, 3, 4])

In [97]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [98]:
a.tolist()

[[1, 2], [3, 4]]

### Array operations

In [99]:
test_a = np.array([[1,2,3],[4,5,6]], float)
test_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [100]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [101]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [102]:
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [103]:
matrix_a = np.arange(1,13).reshape(3,4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

### dot product

In [107]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

In [108]:
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
test_b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [110]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [111]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [113]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [114]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [115]:
test_a.dot(test_a.T)

array([[14, 32],
       [32, 77]])

### all&any

In [116]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
a<0

array([False, False, False, False, False, False, False, False, False,
       False])

In [118]:
np.any(a>5), np.any(a<0)

(True, False)

In [119]:
np.all(a>5), np.all(a<10)

(False, True)

### comparision operation

In [120]:
test_a = np.array([1,3,0], float)
test_b = np.array([5,2,1], float)
test_a > test_b

array([False,  True, False])

In [121]:
test_a == test_b

array([False, False, False])

In [122]:
(test_a > test_b).any()

True

In [124]:
a = np.array([1,3,0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [126]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [127]:
c = np.array([False, True, False], bool)
np.logical_or(b,c)

array([ True,  True,  True])

In [128]:
a

array([1., 3., 0.])

In [129]:
np.where(a > 0, 3, 2)

array([3, 3, 2])

In [130]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [131]:
np.where(a>10)

(array([6, 7, 8, 9], dtype=int64),)

In [132]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [133]:
np.isfinite(a)

array([ True, False, False])

### argmax & argmin

In [134]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a)

(5, 0)

In [136]:
a = np.array([[1,2,4,7], [9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

### boolean index

In [137]:
test_array = np.array([1,4,0,2,3,8,9,7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [138]:
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [139]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

In [140]:
A = np.array([ [12, 13, 14, 12, 16, 14, 11, 10, 9], [11, 14, 12, 15, 15, 16, 10, 12, 11], [10, 12, 12, 15, 14, 16, 10, 12, 12], [ 9, 11, 16, 15, 14, 16, 15, 12, 10], [12, 11, 16, 14, 10, 12, 16, 12, 13], [10, 15, 16, 14, 14, 14, 16, 15, 12], [13, 17, 14, 10, 14, 11, 14, 15, 10], [10, 16, 12, 14, 11, 12, 14, 18, 11], [10, 19, 12, 14, 11, 12, 14, 18, 10], [14, 22, 17, 19, 16, 17, 18, 17, 13], [10, 16, 12, 14, 11, 12, 14, 18, 11], [10, 16, 12, 14, 11, 12, 14, 18, 11], [10, 19, 12, 14, 11, 12, 14, 18, 10], [14, 22, 12, 14, 11, 12, 14, 17, 13], [10, 16, 12, 14, 11, 12, 14, 18, 11]])
B = A < 15 
B

array([[ True,  True,  True,  True, False,  True,  True,  True,  True],
       [ True,  True,  True, False, False, False,  True,  True,  True],
       [ True,  True,  True, False,  True, False,  True,  True,  True],
       [ True,  True, False, False,  True, False, False,  True,  True],
       [ True,  True, False,  True,  True,  True, False,  True,  True],
       [ True, False, False,  True,  True,  True, False, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False, False, False, False, False, False, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False, 

In [141]:
B.astype(np.int)

array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1]])

### fancy index

In [142]:
a = np.array([2,4,6,8], float)

In [143]:
a[a>4]

array([6., 8.])

In [144]:
a.take(b)

array([4., 2., 4.])

In [146]:
a = np.array([[1,4], [9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

In [147]:
a = np.array([[1,4],[9,16]], float)
a[b]

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 9., 16.],
       [ 9., 16.],
       [ 1.,  4.]])

### load txt

In [152]:
a = np.loadtxt("./populations.txt")
a[:10]

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.]])

In [153]:
a_int = a.astype(int)
a_int[:3]

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500]])

In [154]:
np.savetxt('int_data.csv', a_int, delimiter=",")

### numpy object -npy

In [155]:
np.save('npy_test', arr=a_int)

In [156]:
npy_array = np.load(file="npy_test.npy")
npy_array[:3]

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500]])

In [157]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]], int)

In [158]:
np.savetxt('a_npy.txt', a)

In [160]:
a = np.loadtxt('a_npy.txt', dtype=int)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

a = np.loadtxt('a_npy.txt', dtype=float)
a

In [162]:
np.savetxt('a_npy.csv', a)

In [163]:
a = np.loadtxt('a_npy.csv',dtype=int)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [165]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]], int)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [166]:
np.save('bnpy', b)

In [167]:
b = np.load('bnpy.npy')

In [168]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])