# pandas

In [1]:
import pandas as pd 

data_url = '.\data\housing.data'
df_data = pd.read_csv(data_url, sep="\s+", header = None)

In [2]:
df_data.head()

0     1     2   3      4      5     6       7   8      9     10  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3  0.03237   0.0  2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4  0.06905   0.0  2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   

       11    12    13  
0  396.90  4.98  24.0  
1  396.90  9.14  21.6  
2  392.83  4.03  34.7  
3  394.63  2.94  33.4  
4  396.90  5.33  36.2

In [8]:
df_data.columns = ['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','weight_0']
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  weight_0  
0     15.3  396.90   4.98      24.0  
1     17.8  396.90   9.14      21.6  
2     17.8  392.83   4.03      34.7  
3     18.7  394.63   2.94      33.4  
4     18.7  396.90   5.33      36.2

In [9]:
df_data.values

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        2.4000e+01],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        2.1600e+01],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        3.4700e+01],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        2.3900e+01],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        2.2000e+01],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.1900e+01]])

In [11]:
import numpy as np
weight_vector = np.array([[1],[1],[1]])
x_vector = np.array([[3],[4],[5]])

In [12]:
weight_vector.T.dot(x_vector)

array([[12]])

In [13]:
data_url = '.\data\housing.data'
df_data = pd.read_csv(data_url, sep='\s+', header = None)
df_data.columns = ['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','weight_0']
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  weight_0  
0     15.3  396.90   4.98      24.0  
1     17.8  396.90   9.14      21.6  
2     17.8  392.83   4.03      34.7  
3     18.7  394.63   2.94      33.4  
4     18.7  396.90   5.33      36.2

In [18]:
df_data['weight_0'] = 1
df_data = df_data.drop('AGE', axis=1)
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM     DIS  RAD    TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  4.0900    1  296.0     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  4.9671    2  242.0     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  4.9671    2  242.0     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  6.0622    3  222.0     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  6.0622    3  222.0     18.7   

        B  LSTAT  weight_0  
0  396.90   4.98         1  
1  396.90   9.14         1  
2  392.83   4.03         1  
3  394.63   2.94         1  
4  396.90   5.33         1

In [15]:
df_matrix = df_data.as_matrix()
weight_vector = np.random.random_sample((14, 1))

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [16]:
df_matrix.dot(weight_vector)

array([[320.92418   ],
       [288.95766821],
       [276.86443945],
       [254.50335429],
       [260.28928419],
       [262.12434063],
       [335.75448254],
       [354.57641222],
       [359.10314178],
       [347.1335104 ],
       [353.70770048],
       [345.51874707],
       [321.35170825],
       [323.76094769],
       [333.51092838],
       [320.62635184],
       [304.00973213],
       [334.72081018],
       [292.38980501],
       [327.25950729],
       [343.82401534],
       [339.19692505],
       [343.19805671],
       [347.68813446],
       [343.35043809],
       [323.38551432],
       [337.96983242],
       [325.87691146],
       [341.14640169],
       [335.60622519],
       [339.81600916],
       [342.15985371],
       [313.2658657 ],
       [338.07234195],
       [320.94129073],
       [306.37567609],
       [300.11129636],
       [292.28620217],
       [286.14876077],
       [316.92420487],
       [312.85391166],
       [240.17242743],
       [242.14023026],
       [244

In [17]:
df_data.values.dot(weight_vector)

array([[320.92418   ],
       [288.95766821],
       [276.86443945],
       [254.50335429],
       [260.28928419],
       [262.12434063],
       [335.75448254],
       [354.57641222],
       [359.10314178],
       [347.1335104 ],
       [353.70770048],
       [345.51874707],
       [321.35170825],
       [323.76094769],
       [333.51092838],
       [320.62635184],
       [304.00973213],
       [334.72081018],
       [292.38980501],
       [327.25950729],
       [343.82401534],
       [339.19692505],
       [343.19805671],
       [347.68813446],
       [343.35043809],
       [323.38551432],
       [337.96983242],
       [325.87691146],
       [341.14640169],
       [335.60622519],
       [339.81600916],
       [342.15985371],
       [313.2658657 ],
       [338.07234195],
       [320.94129073],
       [306.37567609],
       [300.11129636],
       [292.28620217],
       [286.14876077],
       [316.92420487],
       [312.85391166],
       [240.17242743],
       [242.14023026],
       [244

In [19]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [20]:
list_data = [1,2,3,4,5]
example_obj = Series(data = list_data)
example_obj

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [21]:
list_data = [1,2,3,4,5]
list_name = ["a","b","c","d","e"]
example_obj = Series(data = list_data, index=list_name)
example_obj


a    1
b    2
c    3
d    4
e    5
dtype: int64

In [22]:
example_obj.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [23]:
example_obj.values

array([1, 2, 3, 4, 5], dtype=int64)

In [24]:
type(example_obj.values)

numpy.ndarray

In [25]:
dict_data = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5}
example_obj = Series(dict_data, dtype=np.float32, name='example_data')
example_obj

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: example_data, dtype: float32

In [26]:
example_obj['a']

1.0

In [27]:
example_obj['a'] = 3.2
example_obj

a    3.2
b    2.0
c    3.0
d    4.0
e    5.0
Name: example_data, dtype: float32

In [28]:
example_obj[example_obj > 2]

a    3.2
c    3.0
d    4.0
e    5.0
Name: example_data, dtype: float32

In [29]:
example_obj * 2

a     6.4
b     4.0
c     6.0
d     8.0
e    10.0
Name: example_data, dtype: float32

In [30]:
np.exp(example_obj)

a     24.532532
b      7.389056
c     20.085537
d     54.598148
e    148.413162
Name: example_data, dtype: float32

In [31]:
'b' in example_obj

True

In [32]:
's' in example_obj

False

In [33]:
example_obj.to_dict()

{'a': 3.200000047683716, 'b': 2.0, 'c': 3.0, 'd': 4.0, 'e': 5.0}

In [34]:
example_obj.values

array([3.2, 2. , 3. , 4. , 5. ], dtype=float32)

In [35]:
example_obj.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [36]:
example_obj.name = 'number'
example_obj.index.name = 'alphabet'
example_obj

alphabet
a    3.2
b    2.0
c    3.0
d    4.0
e    5.0
Name: number, dtype: float32

In [37]:
dict_data_1 = {'a':1, "b":2, 'c':3, 'd':4, 'e':5}
indexes = ['a','b','c','d','e','f','g','h']
series_obj_1 = Series(dict_data_1, index=indexes)
series_obj_1

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    NaN
g    NaN
h    NaN
dtype: float64

### dataframe

In [39]:
raw_data = {'first_name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'], 'last_name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze'], 'age': [42, 52, 36, 24, 73], 'city': ['San Francisco', 'Baltimore', 'Miami', 'Douglas', 'Boston']}
df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'city'])
df

first_name last_name  age           city
0      Jason    Miller   42  San Francisco
1      Molly  Jacobson   52      Baltimore
2       Tina       Ali   36          Miami
3       Jake    Milner   24        Douglas
4        Amy     Cooze   73         Boston

In [40]:
DataFrame(raw_data, columns = ['age','city'])

age           city
0   42  San Francisco
1   52      Baltimore
2   36          Miami
3   24        Douglas
4   73         Boston

In [41]:
DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'city', 'debt'])
df.first_name

0    Jason
1    Molly
2     Tina
3     Jake
4      Amy
Name: first_name, dtype: object

In [42]:
df['first_name']

0    Jason
1    Molly
2     Tina
3     Jake
4      Amy
Name: first_name, dtype: object

In [43]:
df.first_name

0    Jason
1    Molly
2     Tina
3     Jake
4      Amy
Name: first_name, dtype: object

In [44]:
df

first_name last_name  age           city
0      Jason    Miller   42  San Francisco
1      Molly  Jacobson   52      Baltimore
2       Tina       Ali   36          Miami
3       Jake    Milner   24        Douglas
4        Amy     Cooze   73         Boston

In [45]:
df.loc[1]

first_name        Molly
last_name      Jacobson
age                  52
city          Baltimore
Name: 1, dtype: object

In [46]:
df['age'].iloc[1:]

1    52
2    36
3    24
4    73
Name: age, dtype: int64

In [47]:
s = pd.Series(np.nan, index=[49,48,47,46,45,1,2,3,4,5])
s.loc[:3]

49   NaN
48   NaN
47   NaN
46   NaN
45   NaN
1    NaN
2    NaN
3    NaN
dtype: float64

In [48]:
s.iloc[:3]

49   NaN
48   NaN
47   NaN
dtype: float64

In [49]:
df.age > 40

0     True
1     True
2    False
3    False
4     True
Name: age, dtype: bool

In [50]:
df.debt = df.age > 40
df

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """Entry point for launching an IPython kernel.


first_name last_name  age           city
0      Jason    Miller   42  San Francisco
1      Molly  Jacobson   52      Baltimore
2       Tina       Ali   36          Miami
3       Jake    Milner   24        Douglas
4        Amy     Cooze   73         Boston

In [51]:
df.to_dict()

{'first_name': {0: 'Jason', 1: 'Molly', 2: 'Tina', 3: 'Jake', 4: 'Amy'},
 'last_name': {0: 'Miller', 1: 'Jacobson', 2: 'Ali', 3: 'Milner', 4: 'Cooze'},
 'age': {0: 42, 1: 52, 2: 36, 3: 24, 4: 73},
 'city': {0: 'San Francisco',
  1: 'Baltimore',
  2: 'Miami',
  3: 'Douglas',
  4: 'Boston'}}

In [52]:
values = Series(data=['M','F','F'], index=[0,1,3])
values

0    M
1    F
3    F
dtype: object

In [53]:
df[:1]

first_name last_name  age           city
0      Jason    Miller   42  San Francisco

In [54]:
df['sex'] = values
df

first_name last_name  age           city  sex
0      Jason    Miller   42  San Francisco    M
1      Molly  Jacobson   52      Baltimore    F
2       Tina       Ali   36          Miami  NaN
3       Jake    Milner   24        Douglas    F
4        Amy     Cooze   73         Boston  NaN

In [55]:
df.T

0          1      2        3       4
first_name          Jason      Molly   Tina     Jake     Amy
last_name          Miller   Jacobson    Ali   Milner   Cooze
age                    42         52     36       24      73
city        San Francisco  Baltimore  Miami  Douglas  Boston
sex                     M          F    NaN        F     NaN

In [56]:
df.values

array([['Jason', 'Miller', 42, 'San Francisco', 'M'],
       ['Molly', 'Jacobson', 52, 'Baltimore', 'F'],
       ['Tina', 'Ali', 36, 'Miami', nan],
       ['Jake', 'Milner', 24, 'Douglas', 'F'],
       ['Amy', 'Cooze', 73, 'Boston', nan]], dtype=object)

In [57]:
df.to_csv('test.csv')

In [58]:
df.head()

first_name last_name  age           city  sex
0      Jason    Miller   42  San Francisco    M
1      Molly  Jacobson   52      Baltimore    F
2       Tina       Ali   36          Miami  NaN
3       Jake    Milner   24        Douglas    F
4        Amy     Cooze   73         Boston  NaN

In [61]:
del df['city']

In [62]:
df

first_name last_name  age  sex
0      Jason    Miller   42    M
1      Molly  Jacobson   52    F
2       Tina       Ali   36  NaN
3       Jake    Milner   24    F
4        Amy     Cooze   73  NaN

In [63]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
DataFrame(pop)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

### Data loading

In [64]:
!conda install --y xlrd

^C


In [3]:
import numpy as np
df = pd.read_excel(".\data\excel-comp-data.xlsx")
df.head()

account                         name                                street  \
0   211829   Kerluke, Koepp and Hilpert                    34456 Sean Highway   
1   320563               Walter-Trantow                     1311 Alvis Tunnel   
2   648336   Bashirian, Kunde and Price  62184 Schamberger Underpass Apt. 231   
3   109996  D'Amore, Gleichner and Bode           155 Fadel Crescent Apt. 144   
4   121213                Bauch-Goldner                   7274 Marissa Common   

              city          state  postal-code     Jan     Feb    Mar  
0       New Jaycob          Texas        28752   10000   62000  35000  
1    Port Khadijah  NorthCarolina        38365   95000   45000  35000  
2   New Lilianland           Iowa        76517   91000  120000  35000  
3       Hyattburgh          Maine        46021   45000  120000  10000  
4  Shanahanchester     California        49681  162000  120000  35000

In [68]:
df['account'].head(2)

0    211829
1    320563
Name: account, dtype: int64

In [69]:
df[['account', 'street', 'state']].head(3)

account                                street          state
0   211829                    34456 Sean Highway          Texas
1   320563                     1311 Alvis Tunnel  NorthCarolina
2   648336  62184 Schamberger Underpass Apt. 231           Iowa

In [70]:
df[:3]

account                        name                                street  \
0   211829  Kerluke, Koepp and Hilpert                    34456 Sean Highway   
1   320563              Walter-Trantow                     1311 Alvis Tunnel   
2   648336  Bashirian, Kunde and Price  62184 Schamberger Underpass Apt. 231   

             city          state  postal-code    Jan     Feb    Mar  
0      New Jaycob          Texas        28752  10000   62000  35000  
1   Port Khadijah  NorthCarolina        38365  95000   45000  35000  
2  New Lilianland           Iowa        76517  91000  120000  35000

In [71]:
df['name'][:3]

0    Kerluke, Koepp and Hilpert
1                Walter-Trantow
2    Bashirian, Kunde and Price
Name: name, dtype: object

In [72]:
account_serires = df['account']
account_serires[:3]

0    211829
1    320563
2    648336
Name: account, dtype: int64

In [73]:
account_serires<250000

0      True
1     False
2     False
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13    False
14    False
Name: account, dtype: bool

In [74]:
account_serires[account_serires<250000]

0     211829
3     109996
4     121213
5     132971
6     145068
7     205217
8     209744
9     212303
10    214098
11    231907
12    242368
Name: account, dtype: int64

In [75]:
df.index = df['account']

In [76]:
df.head()

account                         name  \
account                                         
211829    211829   Kerluke, Koepp and Hilpert   
320563    320563               Walter-Trantow   
648336    648336   Bashirian, Kunde and Price   
109996    109996  D'Amore, Gleichner and Bode   
121213    121213                Bauch-Goldner   

                                       street             city          state  \
account                                                                         
211829                     34456 Sean Highway       New Jaycob          Texas   
320563                      1311 Alvis Tunnel    Port Khadijah  NorthCarolina   
648336   62184 Schamberger Underpass Apt. 231   New Lilianland           Iowa   
109996            155 Fadel Crescent Apt. 144       Hyattburgh          Maine   
121213                    7274 Marissa Common  Shanahanchester     California   

         postal-code     Jan     Feb    Mar  
account                                      
211829         28752   10000   62000  35000  
320563         38365   95000   45000  35000  
648336         76517   91000  120000  35000  
109996         46021   45000  120000  10000  
121213         49681  162000  120000  35000

In [77]:
del df['account']
df.head()

name                                street  \
account                                                                      
211829    Kerluke, Koepp and Hilpert                    34456 Sean Highway   
320563                Walter-Trantow                     1311 Alvis Tunnel   
648336    Bashirian, Kunde and Price  62184 Schamberger Underpass Apt. 231   
109996   D'Amore, Gleichner and Bode           155 Fadel Crescent Apt. 144   
121213                 Bauch-Goldner                   7274 Marissa Common   

                    city          state  postal-code     Jan     Feb    Mar  
account                                                                      
211829        New Jaycob          Texas        28752   10000   62000  35000  
320563     Port Khadijah  NorthCarolina        38365   95000   45000  35000  
648336    New Lilianland           Iowa        76517   91000  120000  35000  
109996        Hyattburgh          Maine        46021   45000  120000  10000  
121213   Shanahanchester     California        49681  162000  120000  35000

In [78]:
df[['name','street']][:2]

name              street
account                                                
211829   Kerluke, Koepp and Hilpert  34456 Sean Highway
320563               Walter-Trantow   1311 Alvis Tunnel

In [79]:
df.loc[[211829,320563],['name','street']]

name              street
account                                                
211829   Kerluke, Koepp and Hilpert  34456 Sean Highway
320563               Walter-Trantow   1311 Alvis Tunnel

In [80]:
df[['name','street']].iloc[:10]

name  \
account                                     
211829         Kerluke, Koepp and Hilpert   
320563                     Walter-Trantow   
648336         Bashirian, Kunde and Price   
109996        D'Amore, Gleichner and Bode   
121213                      Bauch-Goldner   
132971   Williamson, Schumm and Hettinger   
145068                         Casper LLC   
205217                   Kovacek-Johnston   
209744                     Champlin-Morar   
212303                     Gerhold-Maggio   

                                       street  
account                                        
211829                     34456 Sean Highway  
320563                      1311 Alvis Tunnel  
648336   62184 Schamberger Underpass Apt. 231  
109996            155 Fadel Crescent Apt. 144  
121213                    7274 Marissa Common  
132971                   89403 Casimer Spring  
145068           340 Consuela Bridge Apt. 400  
205217           91971 Cronin Vista Suite 601  
209744                       26739 Grant Lock  
212303              366 Maggio Grove Apt. 998

### reindex

In [81]:
df.index =list(range(0,15))
df.head()

name                                street  \
0   Kerluke, Koepp and Hilpert                    34456 Sean Highway   
1               Walter-Trantow                     1311 Alvis Tunnel   
2   Bashirian, Kunde and Price  62184 Schamberger Underpass Apt. 231   
3  D'Amore, Gleichner and Bode           155 Fadel Crescent Apt. 144   
4                Bauch-Goldner                   7274 Marissa Common   

              city          state  postal-code     Jan     Feb    Mar  
0       New Jaycob          Texas        28752   10000   62000  35000  
1    Port Khadijah  NorthCarolina        38365   95000   45000  35000  
2   New Lilianland           Iowa        76517   91000  120000  35000  
3       Hyattburgh          Maine        46021   45000  120000  10000  
4  Shanahanchester     California        49681  162000  120000  35000

### data drop

In [82]:
df

name                                street  \
0         Kerluke, Koepp and Hilpert                    34456 Sean Highway   
1                     Walter-Trantow                     1311 Alvis Tunnel   
2         Bashirian, Kunde and Price  62184 Schamberger Underpass Apt. 231   
3        D'Amore, Gleichner and Bode           155 Fadel Crescent Apt. 144   
4                      Bauch-Goldner                   7274 Marissa Common   
5   Williamson, Schumm and Hettinger                  89403 Casimer Spring   
6                         Casper LLC          340 Consuela Bridge Apt. 400   
7                   Kovacek-Johnston          91971 Cronin Vista Suite 601   
8                     Champlin-Morar                      26739 Grant Lock   
9                     Gerhold-Maggio             366 Maggio Grove Apt. 998   
10       Goodwin, Homenick and Jerde             649 Cierra Forks Apt. 078   
11                        Hahn-Moore              18115 Olivine Throughway   
12      Frami, Anderson and Donnelly                       182 Bertie Road   
13                       Walsh-Haley                  2624 Beatty Parkways   
14                     McDermott PLC                 8917 Bergstrom Meadow   

                 city          state  postal-code     Jan     Feb     Mar  
0          New Jaycob          Texas        28752   10000   62000   35000  
1       Port Khadijah  NorthCarolina        38365   95000   45000   35000  
2      New Lilianland           Iowa        76517   91000  120000   35000  
3          Hyattburgh          Maine        46021   45000  120000   10000  
4     Shanahanchester     California        49681  162000  120000   35000  
5        Jeremieburgh       Arkansas        62785  150000  120000   35000  
6   Lake Gabriellaton     Mississipi        18008   62000  120000   70000  
7          Deronville    RhodeIsland        53461  145000   95000   35000  
8     Lake Juliannton   Pennsylvania        64415   70000   95000   35000  
9           North Ras          Idaho        46308   70000  120000   35000  
10           Rosaberg       Tenessee        47743   45000  120000   55000  
11      Norbertomouth    NorthDakota        31415  150000   10000  162000  
12        East Davian           Iowa        72686  162000  120000   35000  
13       Goodwinmouth    RhodeIsland        31919   55000  120000   35000  
14    Kathryneborough       Delaware        27933  150000  120000   70000

In [83]:
df.drop(1)

name                                street  \
0         Kerluke, Koepp and Hilpert                    34456 Sean Highway   
2         Bashirian, Kunde and Price  62184 Schamberger Underpass Apt. 231   
3        D'Amore, Gleichner and Bode           155 Fadel Crescent Apt. 144   
4                      Bauch-Goldner                   7274 Marissa Common   
5   Williamson, Schumm and Hettinger                  89403 Casimer Spring   
6                         Casper LLC          340 Consuela Bridge Apt. 400   
7                   Kovacek-Johnston          91971 Cronin Vista Suite 601   
8                     Champlin-Morar                      26739 Grant Lock   
9                     Gerhold-Maggio             366 Maggio Grove Apt. 998   
10       Goodwin, Homenick and Jerde             649 Cierra Forks Apt. 078   
11                        Hahn-Moore              18115 Olivine Throughway   
12      Frami, Anderson and Donnelly                       182 Bertie Road   
13                       Walsh-Haley                  2624 Beatty Parkways   
14                     McDermott PLC                 8917 Bergstrom Meadow   

                 city         state  postal-code     Jan     Feb     Mar  
0          New Jaycob         Texas        28752   10000   62000   35000  
2      New Lilianland          Iowa        76517   91000  120000   35000  
3          Hyattburgh         Maine        46021   45000  120000   10000  
4     Shanahanchester    California        49681  162000  120000   35000  
5        Jeremieburgh      Arkansas        62785  150000  120000   35000  
6   Lake Gabriellaton    Mississipi        18008   62000  120000   70000  
7          Deronville   RhodeIsland        53461  145000   95000   35000  
8     Lake Juliannton  Pennsylvania        64415   70000   95000   35000  
9           North Ras         Idaho        46308   70000  120000   35000  
10           Rosaberg      Tenessee        47743   45000  120000   55000  
11      Norbertomouth   NorthDakota        31415  150000   10000  162000  
12        East Davian          Iowa        72686  162000  120000   35000  
13       Goodwinmouth   RhodeIsland        31919   55000  120000   35000  
14    Kathryneborough      Delaware        27933  150000  120000   70000

In [84]:
df

name                                street  \
0         Kerluke, Koepp and Hilpert                    34456 Sean Highway   
1                     Walter-Trantow                     1311 Alvis Tunnel   
2         Bashirian, Kunde and Price  62184 Schamberger Underpass Apt. 231   
3        D'Amore, Gleichner and Bode           155 Fadel Crescent Apt. 144   
4                      Bauch-Goldner                   7274 Marissa Common   
5   Williamson, Schumm and Hettinger                  89403 Casimer Spring   
6                         Casper LLC          340 Consuela Bridge Apt. 400   
7                   Kovacek-Johnston          91971 Cronin Vista Suite 601   
8                     Champlin-Morar                      26739 Grant Lock   
9                     Gerhold-Maggio             366 Maggio Grove Apt. 998   
10       Goodwin, Homenick and Jerde             649 Cierra Forks Apt. 078   
11                        Hahn-Moore              18115 Olivine Throughway   
12      Frami, Anderson and Donnelly                       182 Bertie Road   
13                       Walsh-Haley                  2624 Beatty Parkways   
14                     McDermott PLC                 8917 Bergstrom Meadow   

                 city          state  postal-code     Jan     Feb     Mar  
0          New Jaycob          Texas        28752   10000   62000   35000  
1       Port Khadijah  NorthCarolina        38365   95000   45000   35000  
2      New Lilianland           Iowa        76517   91000  120000   35000  
3          Hyattburgh          Maine        46021   45000  120000   10000  
4     Shanahanchester     California        49681  162000  120000   35000  
5        Jeremieburgh       Arkansas        62785  150000  120000   35000  
6   Lake Gabriellaton     Mississipi        18008   62000  120000   70000  
7          Deronville    RhodeIsland        53461  145000   95000   35000  
8     Lake Juliannton   Pennsylvania        64415   70000   95000   35000  
9           North Ras          Idaho        46308   70000  120000   35000  
10           Rosaberg       Tenessee        47743   45000  120000   55000  
11      Norbertomouth    NorthDakota        31415  150000   10000  162000  
12        East Davian           Iowa        72686  162000  120000   35000  
13       Goodwinmouth    RhodeIsland        31919   55000  120000   35000  
14    Kathryneborough       Delaware        27933  150000  120000   70000

In [85]:
df.drop([0,1,2,3], inplace=True)

In [86]:
df

name                        street  \
4                      Bauch-Goldner           7274 Marissa Common   
5   Williamson, Schumm and Hettinger          89403 Casimer Spring   
6                         Casper LLC  340 Consuela Bridge Apt. 400   
7                   Kovacek-Johnston  91971 Cronin Vista Suite 601   
8                     Champlin-Morar              26739 Grant Lock   
9                     Gerhold-Maggio     366 Maggio Grove Apt. 998   
10       Goodwin, Homenick and Jerde     649 Cierra Forks Apt. 078   
11                        Hahn-Moore      18115 Olivine Throughway   
12      Frami, Anderson and Donnelly               182 Bertie Road   
13                       Walsh-Haley          2624 Beatty Parkways   
14                     McDermott PLC         8917 Bergstrom Meadow   

                 city         state  postal-code     Jan     Feb     Mar  
4     Shanahanchester    California        49681  162000  120000   35000  
5        Jeremieburgh      Arkansas        62785  150000  120000   35000  
6   Lake Gabriellaton    Mississipi        18008   62000  120000   70000  
7          Deronville   RhodeIsland        53461  145000   95000   35000  
8     Lake Juliannton  Pennsylvania        64415   70000   95000   35000  
9           North Ras         Idaho        46308   70000  120000   35000  
10           Rosaberg      Tenessee        47743   45000  120000   55000  
11      Norbertomouth   NorthDakota        31415  150000   10000  162000  
12        East Davian          Iowa        72686  162000  120000   35000  
13       Goodwinmouth   RhodeIsland        31919   55000  120000   35000  
14    Kathryneborough      Delaware        27933  150000  120000   70000

In [89]:
matrix = df.as_matrix()
matrix[:3]

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([['Bauch-Goldner', '7274 Marissa Common', 'Shanahanchester',
        'California', 49681, 162000, 120000, 35000],
       ['Williamson, Schumm and Hettinger', '89403 Casimer Spring',
        'Jeremieburgh', 'Arkansas', 62785, 150000, 120000, 35000],
       ['Casper LLC', '340 Consuela Bridge Apt. 400',
        'Lake Gabriellaton', 'Mississipi', 18008, 62000, 120000, 70000]],
      dtype=object)

In [88]:
matrix[:,-3:]

array([[162000, 120000, 35000],
       [150000, 120000, 35000],
       [62000, 120000, 70000],
       [145000, 95000, 35000],
       [70000, 95000, 35000],
       [70000, 120000, 35000],
       [45000, 120000, 55000],
       [150000, 10000, 162000],
       [162000, 120000, 35000],
       [55000, 120000, 35000],
       [150000, 120000, 70000]], dtype=object)

In [90]:
matrix[:,-3:].sum(axis=1)

array([317000, 305000, 252000, 275000, 200000, 225000, 220000, 322000,
       317000, 210000, 340000], dtype=object)

In [91]:
df.drop('city',axis=1)
df.drop(['city', 'state'], axis=1)

name                        street  \
4                      Bauch-Goldner           7274 Marissa Common   
5   Williamson, Schumm and Hettinger          89403 Casimer Spring   
6                         Casper LLC  340 Consuela Bridge Apt. 400   
7                   Kovacek-Johnston  91971 Cronin Vista Suite 601   
8                     Champlin-Morar              26739 Grant Lock   
9                     Gerhold-Maggio     366 Maggio Grove Apt. 998   
10       Goodwin, Homenick and Jerde     649 Cierra Forks Apt. 078   
11                        Hahn-Moore      18115 Olivine Throughway   
12      Frami, Anderson and Donnelly               182 Bertie Road   
13                       Walsh-Haley          2624 Beatty Parkways   
14                     McDermott PLC         8917 Bergstrom Meadow   

    postal-code     Jan     Feb     Mar  
4         49681  162000  120000   35000  
5         62785  150000  120000   35000  
6         18008   62000  120000   70000  
7         53461  145000   95000   35000  
8         64415   70000   95000   35000  
9         46308   70000  120000   35000  
10        47743   45000  120000   55000  
11        31415  150000   10000  162000  
12        72686  162000  120000   35000  
13        31919   55000  120000   35000  
14        27933  150000  120000   70000

In [92]:
df

name                        street  \
4                      Bauch-Goldner           7274 Marissa Common   
5   Williamson, Schumm and Hettinger          89403 Casimer Spring   
6                         Casper LLC  340 Consuela Bridge Apt. 400   
7                   Kovacek-Johnston  91971 Cronin Vista Suite 601   
8                     Champlin-Morar              26739 Grant Lock   
9                     Gerhold-Maggio     366 Maggio Grove Apt. 998   
10       Goodwin, Homenick and Jerde     649 Cierra Forks Apt. 078   
11                        Hahn-Moore      18115 Olivine Throughway   
12      Frami, Anderson and Donnelly               182 Bertie Road   
13                       Walsh-Haley          2624 Beatty Parkways   
14                     McDermott PLC         8917 Bergstrom Meadow   

                 city         state  postal-code     Jan     Feb     Mar  
4     Shanahanchester    California        49681  162000  120000   35000  
5        Jeremieburgh      Arkansas        62785  150000  120000   35000  
6   Lake Gabriellaton    Mississipi        18008   62000  120000   70000  
7          Deronville   RhodeIsland        53461  145000   95000   35000  
8     Lake Juliannton  Pennsylvania        64415   70000   95000   35000  
9           North Ras         Idaho        46308   70000  120000   35000  
10           Rosaberg      Tenessee        47743   45000  120000   55000  
11      Norbertomouth   NorthDakota        31415  150000   10000  162000  
12        East Davian          Iowa        72686  162000  120000   35000  
13       Goodwinmouth   RhodeIsland        31919   55000  120000   35000  
14    Kathryneborough      Delaware        27933  150000  120000   70000

In [93]:
matrix = df.as_matrix()
matrix

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([['Bauch-Goldner', '7274 Marissa Common', 'Shanahanchester',
        'California', 49681, 162000, 120000, 35000],
       ['Williamson, Schumm and Hettinger', '89403 Casimer Spring',
        'Jeremieburgh', 'Arkansas', 62785, 150000, 120000, 35000],
       ['Casper LLC', '340 Consuela Bridge Apt. 400',
        'Lake Gabriellaton', 'Mississipi', 18008, 62000, 120000, 70000],
       ['Kovacek-Johnston', '91971 Cronin Vista Suite 601', 'Deronville',
        'RhodeIsland', 53461, 145000, 95000, 35000],
       ['Champlin-Morar', '26739 Grant Lock', 'Lake Juliannton',
        'Pennsylvania', 64415, 70000, 95000, 35000],
       ['Gerhold-Maggio', '366 Maggio Grove Apt. 998', 'North Ras',
        'Idaho', 46308, 70000, 120000, 35000],
       ['Goodwin, Homenick and Jerde', '649 Cierra Forks Apt. 078',
        'Rosaberg', 'Tenessee', 47743, 45000, 120000, 55000],
       ['Hahn-Moore', '18115 Olivine Throughway', 'Norbertomouth',
        'NorthDakota', 31415, 150000, 10000, 162000],
       