# 0.0.1 Simple Naive Bayes

In [1]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [3]:
viagra_spam = { 'viagra': [1,0,0,0,0,0,0,0,1,1,1,0,0,1,0,0,0,0,0,1],
'spam': [1,0,0,0,0,0,1,0,1,0, 0,0,0,0,0,0,0,1,1,1]}
df = pd.DataFrame(viagra_spam, columns = ['viagra', 'spam'])
df.head()

viagra  spam
0       1     1
1       0     0
2       0     0
3       0     0
4       0     0

In [4]:
np_data = df.as_matrix()
np_data[:3]

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[1, 1],
       [0, 0],
       [0, 0]], dtype=int64)

In [6]:
p_viagra = sum(np_data[:, 0] == 1) / len(np_data)
p_spam = sum(np_data[:, 1] == 1) / len(np_data)
p_v_cap_s = sum((np_data[:, 0] == 1) & \
(np_data[:, 1] == 1)) / len(np_data)
p_n_v_cap_s = sum((np_data[:, 0] == 0) & \
(np_data[:, 1] == 1)) / len(np_data)

In [7]:
p_spam * (p_v_cap_s / p_spam ) / p_viagra

0.5

In [8]:
p_spam * (p_n_v_cap_s / p_spam ) / (1-p_viagra)

0.2142857142857143

# 0.0.2 German Credit Application

In [10]:
data_url = "./fraud.csv"
df= pd.read_csv(data_url, sep=',')
df.head(10)

ID  History CoApplicant Accommodation  Fraud
0   1  current        none           own   True
1   2     paid        none           own  False
2   3     paid        none           own  False
3   4     paid   guarantor          rent   True
4   5  arrears        none           own  False
5   6  arrears        none           own   True
6   7  current        none           own  False
7   8  arrears        none           own  False
8   9  current        none          rent  False
9  10     none        none           own   True

In [11]:
del df["ID"]
Y_data = df.pop("Fraud")
Y_data = Y_data.as_matrix()
Y_data

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until


array([ True, False, False,  True, False,  True, False, False, False,
        True, False,  True,  True, False, False, False, False, False,
       False, False])

In [12]:
df.head()

History CoApplicant Accommodation
0  current        none           own
1     paid        none           own
2     paid        none           own
3     paid   guarantor          rent
4  arrears        none           own

In [13]:
x_df = pd.get_dummies(df)
x_df.head()

History_arrears  History_current  History_none  History_paid  \
0                0                1             0             0   
1                0                0             0             1   
2                0                0             0             1   
3                0                0             0             1   
4                1                0             0             0   

   CoApplicant_coapplicant  CoApplicant_guarantor  CoApplicant_none  \
0                        0                      0                 1   
1                        0                      0                 1   
2                        0                      0                 1   
3                        0                      1                 0   
4                        0                      0                 1   

   Accommodation_free  Accommodation_own  Accommodation_rent  
0                   0                  1                   0  
1                   0                  1                   0  
2                   0                  1                   0  
3                   0                  0                   1  
4                   0                  1                   0

In [14]:
x_data = x_df.as_matrix()
x_data[:3]

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[0, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0]], dtype=uint8)

In [15]:
Y_data == True

array([ True, False, False,  True, False,  True, False, False, False,
        True, False,  True,  True, False, False, False, False, False,
       False, False])

In [16]:
P_Y_True = sum(Y_data==True) / len(Y_data)
P_Y_False = 1 - P_Y_True

In [17]:
P_Y_True,P_Y_False

(0.3, 0.7)

In [19]:
ix_Y_True = np.where(Y_data)
ix_Y_False = np.where(Y_data==False)
ix_Y_True, ix_Y_False

((array([ 0,  3,  5,  9, 11, 12], dtype=int64),),
 (array([ 1,  2,  4,  6,  7,  8, 10, 13, 14, 15, 16, 17, 18, 19],
        dtype=int64),))

In [21]:
p_x_y_true = (x_data[ix_Y_True].sum(axis=0)) / sum(Y_data==True)
p_x_y_false = (x_data[ix_Y_False].sum(axis=0)) / sum(Y_data==False)
p_x_y_true, p_x_y_false

(array([0.16666667, 0.5       , 0.16666667, 0.16666667, 0.        ,
        0.16666667, 0.83333333, 0.        , 0.66666667, 0.33333333]),
 array([0.42857143, 0.28571429, 0.        , 0.28571429, 0.14285714,
        0.        , 0.85714286, 0.07142857, 0.78571429, 0.14285714]))

In [23]:
x_test = [0,1,0,0,0,1,0,0,1,0]
p_y_true_test = P_Y_True + p_x_y_true.dot(x_test)
p_y_false_test = P_Y_False + p_x_y_false.dot(x_test)
p_y_true_test , p_y_false_test

(1.6333333333333333, 1.7714285714285714)

In [25]:
p_y_true_test < p_y_false_test

True

# 0.0.3 Sklearn Naive Bayes

In [26]:
weather=['Sunny','Sunny','Overcast','Rainy','Rainy',\
'Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',\
'Cool','Mild','Mild','Mild','Hot','Mild']
play=['No','No','Yes','Yes','Yes','No','Yes','No',\
'Yes','Yes','Yes','Yes','Yes','No']

In [27]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
weather_encoded = le.fit_transform(weather)
print(weather_encoded)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [28]:
temp_encoded = le.fit_transform(temp)
label = le.fit_transform(play)
print('Temp', temp_encoded)
print('Play', label)

Temp [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [29]:
features_array = pd.DataFrame({'temp': temp_encoded, 
                              'weather':weather_encoded}).as_matrix()

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [32]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(features_array,label)
predicted = model.predict([[0,2]])
print('Predicted Value:', predicted)

Predicted Value: [1]


In [33]:
from sklearn import datasets

wine = datasets.load_wine()

In [34]:
print('Features:', wine.feature_names)
print('Labels:', wine.target_names)

Features: ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Labels: ['class_0' 'class_1' 'class_2']


In [35]:
wine.data.shape

(178, 13)

In [36]:
print(wine.data[0:5])

[[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
  2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 1.120e+01 1.000e+02 2.650e+00 2.760e+00
  2.600e-01 1.280e+00 4.380e+00 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 1.860e+01 1.010e+02 2.800e+00 3.240e+00
  3.000e-01 2.810e+00 5.680e+00 1.030e+00 3.170e+00 1.185e+03]
 [1.437e+01 1.950e+00 2.500e+00 1.680e+01 1.130e+02 3.850e+00 3.490e+00
  2.400e-01 2.180e+00 7.800e+00 8.600e-01 3.450e+00 1.480e+03]
 [1.324e+01 2.590e+00 2.870e+00 2.100e+01 1.180e+02 2.800e+00 2.690e+00
  3.900e-01 1.820e+00 4.320e+00 1.040e+00 2.930e+00 7.350e+02]]


In [37]:
print(wine.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [40]:
# quiz

# wine data로 naive bayes 예측모델을 만들고 정확도 출력하기

In [41]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.3, 
                                                   random_state=77)

In [42]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)
preds = gnb.predict(x_test)
score = gnb.score(x_test, y_test)
print(score)

1.0
