In [3]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')



In [4]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))


# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        
        
        
"""
x_data = [[0, 0],
          [1, 0],
          [0, 1],
          [1, 1]]
y_data = [[0],
          [1],
          [1],
          [0] 
          ]  """

0 Cost:  8603.155 
Prediction:
 [[235.22784]
 [282.40146]
 [278.39618]
 [303.91577]
 [214.62396]]
10 Cost:  3.1007946 
Prediction:
 [[153.18567]
 [183.80353]
 [181.24045]
 [198.11588]
 [139.42105]]
20 Cost:  3.009819 
Prediction:
 [[152.93187]
 [183.50908]
 [180.94484]
 [197.79417]
 [139.19891]]
30 Cost:  2.9976282 
Prediction:
 [[152.92552]
 [183.51207]
 [180.9423 ]
 [197.79164]
 [139.20363]]
40 Cost:  2.9854767 
Prediction:
 [[152.91992]
 [183.51591]
 [180.94063]
 [197.79004]
 [139.20901]]
50 Cost:  2.97341 
Prediction:
 [[152.91437]
 [183.51978]
 [180.93896]
 [197.78847]
 [139.21439]]
60 Cost:  2.9614062 
Prediction:
 [[152.90884]
 [183.52362]
 [180.93733]
 [197.7869 ]
 [139.21976]]
70 Cost:  2.949487 
Prediction:
 [[152.90329]
 [183.52744]
 [180.93568]
 [197.78532]
 [139.22508]]
80 Cost:  2.9375982 
Prediction:
 [[152.89778]
 [183.53125]
 [180.93404]
 [197.78375]
 [139.23042]]
90 Cost:  2.925771 
Prediction:
 [[152.89229]
 [183.53508]
 [180.93242]
 [197.78221]
 [139.23576]]
100 Cos

'\nx_data = [[0, 0],\n          [1, 0],\n          [0, 1],\n          [1, 1]]\ny_data = [[0],\n          [1],\n          [1],\n          [0] \n          ]  '