In [1]:
import tensorflow as tf

x_data = [[1, 2, 1, 1],  # 특성 데이터 
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]] 

# One-Hot Encoding,  3종류의 결과분류 
y_data = [[0, 0, 1],   #   beginner 회원    
          [0, 0, 1],   #   beginner 회원   
          [0, 0, 1],   #   beginner 회원  
          [0, 1, 0],   #   VIP 회원
          [0, 1, 0],   #   VIP 회원
          [0, 1, 0],   #   VIP 회원
          [1, 0, 0],   #   VVIP 회원 
          [1, 0, 0]]   #   VVIP 회원 

X = tf.placeholder("float", #TODO )
Y = tf.placeholder("float", #TODO )
nb_classes = 3

W = tf.Variable(tf.random_normal(#TODO ), name='weight')
b = tf.Variable(tf.random_normal(#TODO ), name='bias')
 

Instructions for updating:
Colocations handled automatically by placer.


In [2]:
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis =  #TODO 

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.#TODO (learning_rate=0.1).#TODO (cost)

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
        sess.run#TODO  {X: x_data, Y: y_data})
        
        if step % 200 == 0:
            print(step, sess.run(#TODO , feed_dict={X: x_data, Y: y_data}))

    print('--------------')

    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')

    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')

    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')

    all = sess.run(hypothesis, feed_dict={
                   X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

Instructions for updating:
Use tf.cast instead.
0 3.565106
200 0.62345815
400 0.50183076
600 0.40409303
800 0.31075224
1000 0.24047098
1200 0.2168917
1400 0.19757262
1600 0.1813354
1800 0.16749564
2000 0.15556283
--------------
[[1.5953546e-03 9.9839467e-01 9.9961644e-06]] [1]
--------------
[[0.9274914  0.06583215 0.00667636]] [0]
--------------
[[1.7268253e-08 3.6875144e-04 9.9963117e-01]] [2]
--------------
[[1.5953546e-03 9.9839467e-01 9.9961644e-06]
 [9.2749143e-01 6.5832175e-02 6.6763619e-03]
 [1.7268253e-08 3.6875144e-04 9.9963117e-01]] [1 0 2]
